import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(process.cwd(), "..", "..");
const contractsArtifactsDir = path.join(repoRoot, "contracts", "artifacts", "src");
const deploymentsDir = path.join(repoRoot, "contracts", "deployments");
const outputDir = path.join(process.cwd(), "src", "generated");

const CONTRACT_FILES = [
  ["MemoryPass", "MemoryPass.sol", "MemoryPass.json"],
  ["MemoryRegistry", "MemoryRegistry.sol", "MemoryRegistry.json"],
  ["KnowledgePackNFT", "KnowledgePackNFT.sol", "KnowledgePackNFT.json"],
  ["PackLicenseRegistry", "PackLicenseRegistry.sol", "PackLicenseRegistry.json"]
];

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function findLatestDeployment() {
  const files = fs
    .readdirSync(deploymentsDir)
    .filter((file) => file.endsWith(".json"))
    .sort();

  if (files.length === 0) {
    throw new Error("No deployment record found under contracts/deployments");
  }

  return path.join(deploymentsDir, files[files.length - 1]);
}

function toSourceLiteral(value) {
  return JSON.stringify(value, null, 2);
}

fs.mkdirSync(outputDir, { recursive: true });

const generatedAt = new Date().toISOString();
const deploymentPath = findLatestDeployment();
const deployment = readJson(deploymentPath);

const artifacts = {};

for (const [contractName, sourceDir, artifactFile] of CONTRACT_FILES) {
  const artifactPath = path.join(contractsArtifactsDir, sourceDir, artifactFile);
  const artifact = readJson(artifactPath);

  artifacts[contractName] = {
    contractName: artifact.contractName,
    sourceName: artifact.sourceName,
    abi: artifact.abi,
    bytecode: artifact.bytecode ?? "0x",
    deployedBytecode: artifact.deployedBytecode ?? "0x"
  };
}

const contractsTs = `/* eslint-disable */
// Auto-generated by packages/abi/scripts/generate.mjs
// Source deployment: ${path.relative(repoRoot, deploymentPath).replaceAll("\\\\", "/")}
// Generated at: ${generatedAt}

export type KineticsContractName =
  | "MemoryPass"
  | "MemoryRegistry"
  | "KnowledgePackNFT"
  | "PackLicenseRegistry";

export interface KineticsContractArtifact {
  contractName: KineticsContractName;
  sourceName: string;
  abi: readonly unknown[];
  bytecode: string;
  deployedBytecode: string;
}

export const KINETICS_CONTRACT_ARTIFACTS = ${toSourceLiteral(artifacts)} as const satisfies Record<KineticsContractName, KineticsContractArtifact>;

export const MEMORY_PASS_ABI = KINETICS_CONTRACT_ARTIFACTS.MemoryPass.abi;
export const MEMORY_REGISTRY_ABI = KINETICS_CONTRACT_ARTIFACTS.MemoryRegistry.abi;
export const KNOWLEDGE_PACK_NFT_ABI = KINETICS_CONTRACT_ARTIFACTS.KnowledgePackNFT.abi;
export const PACK_LICENSE_REGISTRY_ABI = KINETICS_CONTRACT_ARTIFACTS.PackLicenseRegistry.abi;
`;

const deploymentsTs = `/* eslint-disable */
// Auto-generated by packages/abi/scripts/generate.mjs
// Source deployment: ${path.relative(repoRoot, deploymentPath).replaceAll("\\\\", "/")}
// Generated at: ${generatedAt}

export interface KineticsDeploymentRecord {
  network: string;
  rpcUrl: string;
  deployer: string;
  deployedAt: string;
  contracts: {
    MemoryPass: string;
    MemoryRegistry: string;
    KnowledgePackNFT: string;
    PackLicenseRegistry: string;
  };
}

export const KINETICS_LATEST_DEPLOYMENT = ${toSourceLiteral(deployment)} as const satisfies KineticsDeploymentRecord;

export const KINETICS_DEPLOYED_ADDRESSES = KINETICS_LATEST_DEPLOYMENT.contracts;
`;

const indexTs = `export * from "./generated/contracts.js";
export * from "./generated/deployments.js";
`;

fs.writeFileSync(path.join(outputDir, "contracts.ts"), contractsTs);
fs.writeFileSync(path.join(outputDir, "deployments.ts"), deploymentsTs);
fs.writeFileSync(path.join(process.cwd(), "src", "index.ts"), indexTs);
